import jwt
from django.conf import settings
from rest_framework import authentication, exceptions
from django.contrib.auth.models import AnonymousUser


class SimpleUser:
    """Lightweight user object for JWT auth"""
    def __init__(self, _id: int, username: str):
        self.id = _id
        self.username = username
        self.is_authenticated = True

    def __str__(self):
        return self.username


class CustomJWTAuthentication(authentication.BaseAuthentication):
    """Authenticate requests with tokens generated by Django API using shared secret"""

    def authenticate(self, request):
        auth_header = request.headers.get('Authorization')
        if not auth_header:
            return None  # No credentials, DRF will move to the next auth scheme

        try:
            prefix, token = auth_header.split()
        except ValueError:
            return None

        if prefix.lower() != 'bearer':
            return None

        try:
            payload = jwt.decode(
                token,
                settings.SIMPLE_JWT['SIGNING_KEY'],
                algorithms=['HS256'],
            )
        except jwt.ExpiredSignatureError:
            raise exceptions.AuthenticationFailed('Token expired')
        except jwt.InvalidTokenError:
            raise exceptions.AuthenticationFailed('Invalid token')

        user = SimpleUser(payload.get('id'), payload.get('username'))
        return (user, token)
